### PR TITLE
FDG-8004 Expose all the decimal places for FRN Daily Indexes dataset

### PR DESCRIPTION
**Pull request by hmargy**
https://federal-spending-transparency.atlassian.net/browse/FDG-8004

test coverage: 90.15

### CODE REVIEW

**Comment by chasls2** [comment]
image

On '120 Day Delinquent Debt Referral Compliance Report'
Not sure if this is what its suppose to do or not?  it goes over 9 decimal points

**Comment by hmargy** [comment]
These changes only impact FRN Daily Indexes. Those decimals are correct and are currently in prod for the other dataset. Should be good to move forward without changes

**Comment by hmargy** [comment]
Changes added. Review needed again but should be good to merge after!

**Review by j-hertzler — APPROVED** [review]
Changes look good!

**Pull request merged**
