### PR TITLE
FDG-5328 Update Homepage to Add Explainers Section

### PR DESCRIPTION
**Pull request by jdach**
https://federal-spending-transparency.atlassian.net/browse/FDG-5328
Coverage: 89.12%

### CODE REVIEW

**Comment by wyattch** [comment]
There are a couple of styling points I noticed: 

- It looks like the spacing between the nav bar line and the 'Topics' header needs to be increased slightly (in the mocks it's close to about 32px / 2 rem, right now it is 1.25rem)
- Images look blurred slightly (I believe this was already discussed so perhaps there is something else being done for that)

**Review by wyattch — CHANGES_REQUESTED** [review]
Code looks great, tests and build pass. Really awesome to see MUI grid in action on the site! After styling changes mentioned above are addressed should be good to go. Also, is removing all of the previous banner code ok? Unless the component has no prospect of being re used anywhere I would caution to keep it and simply remove from use for the time being.

**Comment by j-hertzler** [comment]
> Code looks great, tests and build pass. Really awesome to see MUI grid in action on the site! After styling changes mentioned above are addressed should be good to go. Also, is removing all of the previous banner code ok? Unless the component has no prospect of being re used anywhere I would caution to keep it and simply remove from use for the time being.

Had Tom weigh in and we should be good to delete.

**Review by wyattch — APPROVED** [review]
Changes look good. Approved

**Pull request merged**
