### PR TITLE
Matching left distances

### PR DESCRIPTION
**Pull request by chasls2**
https://federal-spending-transparency.atlassian.net/browse/FDG-4806

test: no coverage change

### CODE REVIEW

**Review by jdach — CHANGES_REQUESTED** [review]
- With these changes, the dataset name spacing is now a little off 
image

- There is an extra 4px of padding that was added to the tops of both the bread crumbs and the dataset name

**Comment by chasls2** [comment]
> * With these changes, the dataset name spacing is now a little off
>   image
> * There is an extra 4px of padding that was added to the tops of both the bread crumbs and the dataset name

what screen width is this?

**Comment by chasls2** [comment]
fixed @jdach

**Review by jdach — APPROVED** [review]
Changes look great, approved.

**Pull request merged**
