### PR TITLE
FDG-8569 DDP on the sub-navigation

### PR DESCRIPTION
**Pull request by chasls2**
https://federal-spending-transparency.atlassian.net/browse/FDG-8569

Kylon Conversation about removing's the related dataset form the sub nav. 
https://data-transparency-bfs.slack.com/archives/CPA4LFGMC/p1712859858239699

No change in test coverage

### CODE REVIEW

**Review by jdach — COMMENTED** [review]
On my monitor, the issue has not been resolved. Adding another .5rem just above the footer would fix this, but you may want to check with design. Obviously this is all screen size dependent, so taller screens may still have this issue even after adding more space

**Comment by chasls2** [comment]
> On my monitor, the issue has not been resolved. Adding another .5rem just above the footer would fix this, but you may want to check with design. Obviously this is all screen size dependent, so taller screens may still have this issue even after adding more space

were you 100% or zoomed out more? I couldn't see the issue at 100% across the screen sizes I test. But Ill double check

**Comment by chasls2** [comment]
Ticket is ready for rereview.

**Review by jdach — APPROVED** [review]
The new design changes look great!

**Pull request merged**
