### PR TITLE
FDG-8007 Published Reports - Whitelist - Upcoming Auctions Dataset

### PR DESCRIPTION
**Pull request by j-hertzler**
https://federal-spending-transparency.atlassian.net/browse/FDG-8007

No change in coverage

### CODE REVIEW

**Review by hmargy — COMMENTED** [review]
Sorting for security types should go (Bills > Notes > Bonds > TIPS > FRNs). Need to follow up with Data about this change before approving

**Comment by j-hertzler** [comment]
> Sorting for security types should go (Bills > Notes > Bonds > TIPS > FRNs). Need to follow up with Data about this change before approving

PR has been repurposed to include just whitelisting the published report

**Review by hmargy — APPROVED** [review]
changes look good!

**Comment by hmargy** [comment]
looks good! Merging!

**Pull request merged**
