### PR TITLE
FDG-7051 Correct Number of Decimal Places for Tool

### PR DESCRIPTION
**Pull request by wyattch**
Coverage: 90.20%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7051

### CODE REVIEW

**Comment by tompurkaple** [comment]
NOTE: DO NOT MERGE until hotfix process completed on 3/31

**Review by tompurkaple — COMMENTED** [review]
I stumbled on a weird issue that doesn't seem to happen in the version currently in prod.

When I first load the page and drag my mouse to select all the contents in the US dollar value input:
Screenshot 2023-04-03 120715

...and then type a "2" to replace the highlighted "1.00", the euro value updates to "2":
Screenshot 2023-04-03 120750

**Comment by wyattch** [comment]
This issue was caused by toFixed(), rounding now only depends on Math.round()

**Review by tompurkaple — APPROVED** [review]
Changes look good. Seems to function correctly locally and passes unit tests.

**Pull request merged**
